### ISSUE TITLE
Add Spiegel online

### ISSUE THREAD

**Issue by guerda** [svenjacobs/leon#139]
Spiegel.de seems to use tracking parameters as well, I suspect from the app. Example:
https://www.spiegel.de/netzwelt/elon-musk-twitter-sperrt-konten-mehrerer-journalisten-von-new-york-times-washington-post-etc-a-040213a0-aa1e-4627-9a5a-69d5f4f929fb?sara_ecid=soci_upd_KsBF0AFjflf0DZCxpPYDCQgO1dEMph

I will try to provide a filter as previously

**Comment by svenjacobs** [comment]
Hey @guerda, how are you coming along with the Spiegel sanitizer?

**Comment by guerda** [comment]
Haven't had the chance yet to look into this. Maybe next week
