### ISSUE TITLE
What is this smile in the cleaned URL? I never seen before

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#140]
![Screenshot_2022-12-21-21-53-56-64_2283887740e0598c1c826260c5e5be76 (1)](https://user-images.githubusercontent.com/113377431/209066540-e1082fdf-5f08-42f7-8642-d819a9011aa3.jpg)

**Comment by svenjacobs** [comment]
[Amazon Smile](https://smile.amazon.com/) is a donation program where Amazon donates a percentage of your purchases to charities. Apparently it's not available everywhere, like in Italy. Please just disable Amazon Smile in the settings of Leon. Thank you 🙂
