### ISSUE TITLE
[Feature Request] Malaysian Alternatives to Amazon/Ebay (Lazada and Shopee)

### ISSUE THREAD

**Issue by ixanza** [svenjacobs/leon#145]
I have 2 examples of apps here which could benefit from some cleaning

1. [Lazada](https://play.google.com/store/apps/details?id=com.lazada.android)
2. [Shopee](https://play.google.com/store/apps/details?id=com.shopee.my)

The URL when sharing items in Lazada is shortened which would need to be decoded. Example is 
[https://s.lazada.com.my/s.fp03W](https://s.lazada.com.my/s.fp03W) which becomes 
`https://www.lazada.com.my/products/100-cotton-jogger-6-poket-kain-tebal-cargo-pant-multi-pocket-seluar-kerja-i3103291614-s15547124539.html?dsource=share&laz_share_info=9532664_100_100_5449387_9533664_null&laz_token=d994010eeff70e9df2d3f465d5b0e727&exlaz=e_RtJqWofx9nLGip8qo24MCTJQcHdSbil0861t6ae%2Fu4vCXvTKdNAtBWNri5zqcNlYb9yEAKGsy7Oyw%2BVOW%2F%2FthI73bSZ6YkVRD3WnASIas1Y%3D&sub_aff_id=social_share&sub_id2=9532664&sub_id3=5449387&sub_id6=CPI_EXLAZ`

However only `https://www.lazada.com.my/products/100-cotton-jogger-6-poket-kain-tebal-cargo-pant-multi-pocket-seluar-kerja-i3103291614-s15547124539.html` is relevant

The URL when sharing items in Shopee is simpler. Example would be
[https://shopee.com.my/product/300862466/12251369135?smtt=O.123661111-1672730601.9](https://shopee.com.my/product/300862466/12251369135?smtt=O.123661111-1672730601.9)

Only relevant bit is up to ?smtt: `https://shopee.com.my/product/300862466/12251369135`

**Comment by svenjacobs** [comment]
Hello @ixanza, thanks for your feedback.

We can add sanitizers for Lazada and Shopee, that's no problem. However Leon cannot unfold the Lazada short URL (`s.lazada.com.my`). If you want to know why, please have a look at [this discussion](https://github.com/svenjacobs/leon/discussions/80).

**Comment by ixanza** [comment]
Thanks for the reply and noted on the discussion. I can use another app to evaluate the short URL

**Comment by svenjacobs** [comment]
@ixanza Do you maybe want to develop the sanitizers for Lazada and Shopee? 😃

**Comment by svenjacobs** [comment]
Both sanitizers have been added and will be available in the next release.

**Comment by svenjacobs** [comment]
@all-contributors please add @ixanza for ideas
