### ISSUE TITLE
Problem with amazon links

### ISSUE THREAD

**Issue by Domefemia** [svenjacobs/leon#149]
Hi, nice app by the way,
I want to report a problem there is for amazon link, it's pretty simple, 
if the app detect an www.amazon link give as a result a smile.amazon, but this url it's only valid for the .com/.de domains site, and not for other domains like the it/uk/es/jp etc.. 
On the other hand there are domains that only redirect you to the normal amazon site for example smile.amazon.au, soo it's not worth to do this change to the link!

**Comment by svenjacobs** [comment]
Hello, thanks for the report. Please disable the Amazon Smile sanitizer as described [here](https://github.com/svenjacobs/leon/issues/140). Thank you 🙂
