### ISSUE TITLE
CMP query string in The Guardian links

### ISSUE THREAD

**Issue by codeinabox** [svenjacobs/leon#151]
Firstly thank you for such a great useful open source tool! I have a question, I tried sanitising the following link from The Guardian and the link was unchanged

> https://www.theguardian.com/world/2023/jan/15/nepal-plane-crash-with-72-onboard-leaves-at-least-16-dead?CMP=Share_AndroidApp_Other

Should the CMP query string, which indicates how the link was shared, be removed or is that outside the scope of this tool? If It should be removed, I am happy to raise a PR for a new sanitiser

**Comment by svenjacobs** [comment]
Hello @codeinabox,

thanks for your feedback. Any parameters that are not relevant for the proper functionality of the site should be removed. So I would be happy about a pull request 😃

**Comment by svenjacobs** [comment]
Hello @codeinabox,

do you still want to provide a PR? 😃

**Comment by codeinabox** [comment]
I don't think I'll have time to do this, so I'm going to close this issue

**Comment by svenjacobs** [comment]
This has been added and will be available in the next release 😃
