### ISSUE TITLE
Remove substring and decode rest

### ISSUE THREAD

**Issue by gl-dev** [svenjacobs/leon#159]
Here is an example of a combined link with a tracker/redirector and a encoded URL

https://www.jdoqocy.com/click-7988170-15232592?SID=11003b6m4t07&url=https%3A%2F%2Fwww.gog.com%2Fde%2Fgame%2Falwas_awakening

Cleaning would require to cut the string up to the second "https" with decoding afterwards.
Maybe such a feature could be implemented?

**Comment by svenjacobs** [comment]
Yes, we already have sanitizers that work similarly like [GoogleSearchSanitizer](https://github.com/svenjacobs/leon/blob/807da3c9685f48b4fe1db598e037773a06753201/core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/google/GoogleSearchSanitizer.kt) so a sanitizer for `jdoqocy.com` just needs to be added. Do you maybe want to step in here?

**Comment by gl-dev** [comment]
Thank you guys! 😊

**Comment by svenjacobs** [comment]
@all-contributors please add @gl-dev for ideas. please add @aleksandarzekovic for code.
