### ISSUE TITLE
[AmazonProduct] Shorten links even more

### ISSUE THREAD

**Issue by felixschndr** [svenjacobs/leon#168]
Hey there! I love your work, really appreciate it =)

I found something for the amazon product link shortener:
- Input link: `https://www.amazon.de/Xiaomi-Aktivit%C3%A4tstracker-Trainings-Puls%C3%BCberwachung-Akkulaufzeit/dp/B091G3FLL7/?_encoding=UTF8&pd_rd_w=xDcJP&pf_rd_p=bf172aca-3277-41f6-babb-6ce7fc34cf7f&pf_rd_r=ZC6FZ5G6W9K8DEZTPBYW&pd_rd_r=11b3ec4e-047c-4f37-8302-62dedb8f502b&pd_rd_wg=Ozi90&ref_=pd_gw_ci_mcx_mr_hp_atf_m`
- Gets converted to: `https://www.amazon.de/Xiaomi-Aktivit%C3%A4tstracker-Trainings-Puls%C3%BCberwachung-Akkulaufzeit/dp/B091G3FLL7/` (which is good...)
- ... But it can be shortened even more: `https://www.amazon.de/dp/B091G3FLL7/`. Only the `/dp/` followed by the product id is a valid amazon link as well and in some cases (where the product title is long) can be much shorter

So [this](https://github.com/svenjacobs/leon/blob/7b19a7e02872d22b7b980b4df662c875650e81be/core-domain/src/test/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/amazon/AmazonProductSanitizerTest.kt#L39) should be `result shouldBe "https://www.amazon.de/dp/B091G3FLL7/"`

----

Furthermore I think there might be a test missing for links from other countries like `.co.uk` (multiple dots)

**Comment by svenjacobs** [comment]
This will be available in the next release 😃

**Comment by felixschndr** [comment]
Nice!

**Comment by TPS** [comment]
Duplicates https://github.com/svenjacobs/leon/discussions/160, but I'm glad it's fixed from here.

**Comment by TPS** [comment]
> This trick works also with amazon.it

It's frankly likely it works across _all_ of Amazon.[TLD].  @svenjacobs Is there a method setup for that sort of thing in Léon?

**Comment by svenjacobs** [comment]
> > This trick works also with amazon.it
> 
> It's frankly likely it works across _all_ of Amazon.[TLD].  @svenjacobs Is there a method setup for that sort of thing in Léon?

Yes, the underlying regex is designed so that it works with all Amazon domains. @TPS What should the method set up?

**Comment by TPS** [comment]
I meant something that could work across many TLDs, but the same owner & pattern (like Amazon's above or [Google's](https://www.google.com/supported_domains).

**Comment by svenjacobs** [comment]
> I meant something that could work across many TLDs, but the same owner & pattern (like Amazon's above or [Google's](https://www.google.com/supported_domains)).

@TPS I still don't understand, sorry 😉 When we write a sanitizer for a domain that is known to have multiple TLDs, we generally design the regex as such. I don't know if it makes sense to have an option that makes any TLDs available for all existing sanitizers?

**Comment by TPS** [comment]
> @TPS I still don't understand, sorry 😉 When we write a sanitizer for a domain that is known to have multiple TLDs, we generally design the regex as such.

This is what I was verifying, & whether that was done for, e.g., Amazon.[TLD], Google.[TLD], &c

> I don't know if it makes sense to have an option that makes any TLDs available for all existing sanitizers?

No, certainly not _generally_, but, if turns out that existing/requested sanitizer needed to be written wide enough for `Example.`[TLD], I now know it _could_.  Thanks!

**Comment by TPS** [comment]
@svenjacobs This is now badly broken in latest F-Droid release v45.

E.g., random product `https://www.amazon.com/Introduction-F-Droid-Software-Repository-Android-ebook/dp/B0CSQF62GW/ref=mp_s_a_1_1?crid=K5YJ0LDMNB9C&dib=eyJ2IjoiMSJ9.dqQNtNLwNfdxLT96VfO1ZhX3Pi6bOLAZ4hmf-SutDkyjPabF5rQzxcAxznFiuulwTkZsxbF8o0XdEOXdrrm8McZnbdd1eV8z8drW-enxd_xQauyZfcHcZaY4GHVmqkn2kD_rJ6ZDpFmalm4YqnDUkGEuNJNryaHkVgopAhYGx4O0i0JawSjkDBV7Bm8F1oprRQrFH_HK2lM6R5PKLEteQg.hm7HbJcGi2jo4SbvqD6KderwayfYHCUQkqw0uKjbjfg&dib_tag=se&keywords=F-Droid&qid=1730436319&sprefix=f-droid%2Caps%2C190&sr=8-1`

should be (& Léon _shows_)

`https://www.amazon.com/dp/B0CSQF62GW/`

but actually opens

`http://www.amazon.com/gp/aw/d/B0CSQF62GW/aiv/detailpage/`

which is completely broken.

**Comment by svenjacobs** [comment]
@TPS @serrq Are you sure this wasn't a temporary issue with Amazon? I cannot reproduce this behaviour with Leon v45 from F-Droid. Leon opens the URL that is shown.

![Screenshot_20241101_110644](https://github.com/user-attachments/assets/110d23b9-a169-4b04-9467-87be18519556)

**Comment by svenjacobs** [comment]
> I remember I had an issue with 45 but I am not sure about what.
> 
> Next time I past here the result and more details.

Can you confirm that Amazon is now working again?

**Comment by TPS** [comment]
@svenjacobs I copied that broken URL from Intent Intercept directly after Léon, so it's _not_ a site issue.  As mentioned, Léon _shows_ the correctly cleaned URL, but doesn't open it.

N.B.:  I keep the decode option on always & the URL-only option the default always off, but that doesn't seem to change anything here.

**Comment by svenjacobs** [comment]
> Léon _shows_ the correctly cleaned URL, but doesn't open it.

That is impossible. Leon opens exactly the URL that it displays. Also there are no mentions of `aiv/detailpage/` in the source code of Leon. Please verify if your browser makes any redirects when opening `https://www.amazon.com/dp/B0CSQF62GW/`. Maybe it's a regional issue with Amazon?

**Comment by TPS** [comment]
@svenjacobs Would you mind installing II as detailed before & checking?  I can reproduce @ will, even on correctly-cleaned URLs. 🤷🏾‍♂️

**Comment by TPS** [comment]
Nm, I figured it out & apologize deeply.  It's a bug w/ [OLW](https://f-droid.org/packages/com.tasomaniac.openwith.floss/) which I forgot was in the chain.  I'll open a ticket there.

**Comment by svenjacobs** [comment]
Nevermind. I'm glad you found the source of the issue!

**Comment by svenjacobs** [comment]
> It seems working fine but I think the issue only happen with the parameter

Please read the previous comments. It was not an issue with Leon. It was a false alarm.
