### ISSUE TITLE
[Feature Request] Clean pearl.de newsletter links

### ISSUE THREAD

**Issue by ma651851384** [svenjacobs/leon#177]
Hi!
I am a customer of pearl.de. After I have subscribed to their newsletter, I regularly getting the email newsletter from them with a included link to offers. Unfortunately, until few months the link to the offers includes tracking parameter.

My feature request: Please provide the "cleaned up" link/URL of their offerer URLs.

Example for the (bad) link from the email:
`https://www.pearl.de/m/10884/?vid=985&curr=DEM&wa_id=995&wa_num=10884&mt=bWsqHZ2EOdIMxzpUi7oRsjVMLsC2%2Fyc65JwkwDStD1WiEu3REqi2%2Fw%3D%3D&utm_source=10884&utm_medium=onlineversion_D`

The following link works well without that bad tracking information (all after "?"):
`https://www.pearl.de/m/10884/`

Thanks a lot for your work

Matthias

**Comment by svenjacobs** [comment]
Done. Will be available in the next release.

**Comment by svenjacobs** [comment]
@all-contributors please add @ma651851384 for ideas

**Comment by ma651851384** [comment]
Nice work! I regularly (weekly) use the app to open that shop newsletter. Without tracking, thx to your work.

:+1:
