### ISSUE TITLE
Add domain based rules

### ISSUE THREAD

**Issue by adeekshith** [svenjacobs/leon#18]
First of all, thanks for this project! Found this from [F-droid circles](https://mastodon.technology/@IzzyOnDroid/106373635637389989) and loved the idea❣️

What do you think about adding domain specific rules to clean URLs like these:

`https://www.amazon.com/BEAST-40oz-Black-Tumbler-Stainless/dp/B08GTPXJBL/?_encoding=UTF8&smid=AHFMMW9O1FG2X&pf_rd_p=d11c243d-9bba-498d-bb87-2e184199c856&pd_rd_wg=zP7f5&pf_rd_r=43Z35PH2XY62GBS2WZ7J&pd_rd_w=2b5Rj&pd_rd_r=7cd0fb38-2890-4adc-b51e-b12056bd09ec`
➔
`https://www.amazon.com/BEAST-40oz-Black-Tumbler-Stainless/dp/B08GTPXJBL/`

May be the rule can be:
`www.amazon.com/(.*)/dp/([0-9A-Z]+)/* -> www.amazon.com/$1/dp/$2/`

Great app and clean code! Thank you!!

**Comment by svenjacobs** [comment]
Hi Deekshith,

thanks for your feedback ❤️ 

After cleaning an URL, the app presents the number of removed parameters to the user. This is currently based on the number of found regex groups. So the regex would have to be slightly modified to catch each parameter individually. I will certainly work on this.

Thank you.

**Comment by svenjacobs** [comment]
This has been added to version 0.5.0. The update should be available on Google Play soon and on F-Droid in a few days.

**Comment by adeekshith** [comment]
Woohoo! Awesome @svenjacobs 😃🎉

**Comment by svenjacobs** [comment]
Unfortunately I forgot to add a database migration to 0.5.0. Should the app crash immediately after startup, please just delete app data and everything should be fine. Sorry for the inconvenience.

**Comment by TPS** [comment]
@svenjacobs Is it possible to add the functionality from [Amazon Smile Redirect](https://github.com/webdevnerdstuff/amazon-smile-redirect) to Léon (e.g., convert www.Amazon.[com|co.uk|de] links to Smile.Amazon.[com|co.uk|de])?

**Comment by svenjacobs** [comment]
> @svenjacobs Is it possible to add the functionality from [Amazon Smile Redirect](https://github.com/webdevnerdstuff/amazon-smile-redirect) to Léon (e.g., convert [www.Amazon.[com|co.uk|de]](http://www.Amazon.%5Bcom%7Cco.uk%7Cde%5D) links to Smile.Amazon.[com|co.uk|de])?

Yes, this would be possible. However this would slightly change the purpose of Leon from a URL cleaner to a URL rewriter? Please create a new issue where we can discuss this further. Thanks 😃

**Comment by TPS** [comment]
> May be the rule can be:
> `www.amazon.com/(.*)/dp/([0-9A-Z]+)/* -> www.amazon.com/$1/dp/$2/`

Technically, the string that `$1` matches isn't required, either.  Amazon's happy w/ solely the `/dp/$2` portion.

**Comment by TPS** [comment]
@svenjacobs When navigating Amazon's site, almost all the non-product links have `ref` or `ref_` parameters which need to be stripped, also.

**Comment by svenjacobs** [comment]
@TPS Please create a new issue for this. Thank you 😃
