### ISSUE TITLE
Clean YouTube-URLs

### ISSUE THREAD

**Issue by Glitchy-Tozier** [svenjacobs/leon#185]
Hi, love the design of this app! One thing I've noticed is that this tracking-parameter doesn't get removed from YouTube URLs. No idea what it does, but the link works perfectly fine without it.
```
Original:
https://m.youtube.com/watch?v=CvFH_6DNRCY&pp=ygUHZGVidXNzeQ%3D%3D
Current:
https://m.youtube.com/watch?v=CvFH_6DNRCY&pp=ygUHZGVidXNzeQ%3D%3D
Ideal:
https://m.youtube.com/watch?v=CvFH_6DNRCY
```
![Screenshot_20230603-082730_URL Cleaner.jpg](https://github.com/svenjacobs/leon/assets/59611881/e136281f-0637-40a8-a1f1-32d860fd37b0)

I'm using version v28.

**Comment by svenjacobs** [comment]
Hello @Glitchy-Tozier, thanks for your feedback 😃 

The existing YouTube sanitizer needs to be adjust to also take the `pp` parameter into account.

**Comment by Glitchy-Tozier** [comment]
Nice :confetti_ball:

**Comment by svenjacobs** [comment]
@all-contributors please add @Glitchy-Tozier for ideas
