### ISSUE TITLE
Adding "default browser" inside Leon for quick "open" action

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#186]
It needs of "exit browser" default setting. Because after I click the "open" button Leon must pass the cleaned URL to default browser.

**Comment by svenjacobs** [comment]
Hello @serrq,

I don't quite understand your feature request. If you have multiple browser installed, when clicking the "open" button there should be a share dialog where you can select the desired browser. Usually you can select between "open once" or "open always" (making this browser the default). This is the standard behaviour of Android and does not have anything to do with Leon. On more modern Android OS versions there is a dedicated system setting for the default browser which Leon will stick to. Again, this is just the standard behaviour when sending an [Intent](https://developer.android.com/reference/android/content/Intent) to the system.

**Comment by svenjacobs** [comment]
> Is it a bug or is it what you expect your app to do?

Interesting. This is a bug. I will have a look into it.

**Comment by svenjacobs** [comment]
Yes, I understand the problem. I just need to think about a solution 😉

**Comment by devnoname120** [comment]
Being able to set Leon as the default browser would be super convenient. Leon would immediately sanitize the URL and pass on the intent to the actual browser (chosen by the user).

**Comment by svenjacobs** [comment]
Hello all,

after thinking about this a bit more unfortunately I must say that this is not possible. Once Leon is set as the default browser, it's not possible to open another browser when clicking "Open". It is a (deliberate?) [limitation](https://github.com/svenjacobs/leon/issues/372#issuecomment-2366820793) of the Android operating system. Once a default browser is set, the system won't let you choose another browser when opening an URL, even if you explicitly ask to do so in code.

The only solution you have is to copy the cleaned URL and manually paste it into your browser. I'm sorry!

**Comment by svenjacobs** [comment]
> Would it not work to call the chosen browser activity directly? Users could then either choose from a list of installed browsers (you can maintain a whitelist of known apps that are browsers), or manually write the full intent name.

Querying for installed browsers is not possible as I have mentioned [here](https://github.com/svenjacobs/leon/issues/372#issuecomment-2366820793).

I would have to maintain a list of known browser packages. I would have to keep this list up-to-date. I would have to manually query if one or more of these browsers are installed. I would also have to build my own chooser dialog to select the desired browser where the link should open. All in all I think this is a very fragile and high-maintenance solution 😞

**Comment by devnoname120** [comment]
@svenjacobs Would it work if the device is rooted?

**Comment by svenjacobs** [comment]
> @svenjacobs Would it work if the device is rooted?

Maybe, I don't know.

**Comment by TPS** [comment]
> Querying for installed browsers is not possible as I have mentioned [here](https://github.com/svenjacobs/leon/issues/372#issuecomment-2366820793).
> 
> I would have to maintain a list of known browser packages. I would have to keep this list up-to-date. I would have to manually query if one or more of these browsers are installed. I would also have to build my own chooser dialog to select the desired browser where the link should open. All in all I think this is a very fragile and high-maintenance solution 😞

@svenjacobs I believe this isn't correct.  [OLW](https://github.com/tasomaniac/OpenLinkWith) does this _very_ well, a certain bug notwithstanding.

**Comment by svenjacobs** [comment]
> @svenjacobs I believe this isn't correct. [OLW](https://github.com/tasomaniac/OpenLinkWith) does this _very_ well, [a certain bug](https://github.com/svenjacobs/leon/issues/168#issuecomment-2451774447) notwithstanding.

[This](https://github.com/tasomaniac/OpenLinkWith/blob/ae55b1854c5ce4e65b7f1ba85457cd3bff78dcbd/browser-resolver/src/main/kotlin/com/tasomaniac/openwith/browser/resolver/BrowserResolver.kt#L33-L46) is how they do it. The error in my case was that I used `PackageManager.MATCH_DEFAULT_ONLY` instead of `PackageManager.MATCH_ALL` 🤦🏼‍♂️ So I **can** query for installed browsers **BUT** [this comment](https://github.com/svenjacobs/leon/issues/372#issuecomment-2365258164) is still true. Even when using `Intent.createChooser`, we still don't see the system chooser and Android only opens the default browser. What OLW did is they built their own chooser dialog, which Leon would also have to do as I mentioned earlier.
