### ISSUE TITLE
Cleaner for CX analytics

### ISSUE THREAD

**Issue by gavanore** [svenjacobs/leon#188]
Looks like they use `cx_` in the same way Google uses `utm_`. With some other weird additions like `mibextid` and the `cxrecs_s` anchor.

I found an example in the wild here:

`https://www.redacted.com/redacted/2023/06/01/page-of-article.html?cx_testId=40&cx_testVariant=cx_8&cx_artPos=4&mibextid=Zxz2cZ#cxrecs_s`

I deleted everything and the page rendered with no issues, as in the following:

`https://www.redacted.com/redacted/2023/06/01/page-of-article.html`

I could contribute this myself, if you would welcome a PR.

**Comment by gavanore** [comment]
OK great. Been looking to do something real vs theoretical with Kotlin. :)

I'll work up something for you to review.

**Comment by svenjacobs** [comment]
@all-contributors please add @gavanore for ideas
