### ISSUE TITLE
[Feature Request] Clean Google Click ID (gclid) from urls

### ISSUE THREAD

**Issue by guerda** [svenjacobs/leon#190]
It seems that google analytics is adding a glcid parameter into shared urls on many websites.

This looks like this then:

    https://example.com/?country=de&gclid=Cj0KCQjw7aqkBhDPARIsAKGa0oLfaxdU3u0Xc9_UXqBYN9Fkx3Ddt7I5O17Df8KjYTMJGRBh9AV_6pkaAp39EALw_wcF

I stumbled upon this parameter on different websites already and it would be great if Leon would clean this, too

Google Click ID documentation 
https://support.google.com/google-ads/answer/9744275?hl=en

It looks like it's automatically added to urls when using the share functionality via Safari or Chrome.

**Comment by guerda** [comment]
I tested it out with the debug build from the CI and it works fine. Thank you for reviewing and mergin it so fast!

**Comment by svenjacobs** [comment]
Thank you for the PR! 👍🏼
