### ISSUE TITLE
Support for Spotify URLs

### ISSUE THREAD

**Issue by vrindavan** [svenjacobs/leon#198]
The App fails to clean Spotify's URLs.

**Original**: https://open.spotify.com/track/5LEbg97KkVmAv9qHR7bS59?si=CXCVCQplRkqNtDWW42dXgA&context=spotify%3Aplaylist%3A37i9dQZF1EpjSENbNnZRJr

**Cleaned**: https://open.spotify.com/track/5LEbg97KkVmAv9qHR7bS59

**Params**: si, context

**Comment by svenjacobs** [comment]
There is already a Spotify sanitizer but the parameters are missing. Going to fix this.

**Comment by svenjacobs** [comment]
@all-contributors please add @vrndavn for bug
