### ISSUE TITLE
Support for Threads URLs

### ISSUE THREAD

**Issue by vrindavan** [svenjacobs/leon#199]
The App fails to clean Threads' URLs.

**Original**: https://www.threads.net/t/CufR4M8yNdJ/?igshid=NTc4MTIwNjQ2YQ==

**Cleaned**: https://www.threads.net/t/CufR4M8yNdJ

**Params**: igshid

This is the same param from Instagram and it works with IG links.

**Comment by svenjacobs** [comment]
Yes, we need a sanitizer for Threads 😉 I'm going to assume that all parameters can be removed.

**Comment by svenjacobs** [comment]
@all-contributors please add @vrndavn for ideas
