### ISSUE TITLE
Add ?fbclid=

### ISSUE THREAD

**Issue by jimcarst** [svenjacobs/leon#20]
Hi!
Awesome idea for an app.

I tested a link that contained a tracker that started with `?fbclid=`, and it was not recognised.

Cheers!

**Comment by svenjacobs** [comment]
Hi Jim, thanks for your feedback! I will add this parameter to the Facebook sanitizer.

**Comment by svenjacobs** [comment]
This has been added to version 0.5.0. The update should be available on Google Play soon and on F-Droid in a few days.

**Comment by svenjacobs** [comment]
Unfortunately I forgot to add a database migration to 0.5.0. Should the app crash immediately after startup, please just delete app data and everything should be fine. Sorry for the inconvenience.
