### ISSUE TITLE
Default decode and extract options

### ISSUE THREAD

**Issue by BrajBliss** [svenjacobs/leon#200]
An option to enable these before importing an URL so we don't have to always turn these options on or off.

**Comment by svenjacobs** [comment]
Hello @vrindavan,

do you have an example of a URL that always needs to be decoded? Of course what I could do is remember the states of these toggles.

**Comment by vrindavan** [comment]
I was referring to all URLs in general. You can consider the Spotify or Threads URL for instance (_previous issues_). An option to remember states would be better.

I use Twitter and Spotify URLs mostly.

**Comment by svenjacobs** [comment]
Just to be clear: The "decode" toggle means to decode an URL which was [URL encoded](https://en.wikipedia.org/wiki/URL_encoding). See #49 why this was added. Usually this option is not required.

**Comment by vrindavan** [comment]
Sure. I was talking about extract only.

**Comment by svenjacobs** [comment]
> Also my RSS reader breaks the ***** with article title + url (merged).

Sorry I don't understand. How is this related to the decode and extract toggles?

**Comment by svenjacobs** [comment]
Could you please provide an example of the text that your RSS shares and what Leon does with it. When you use "extract", does it not work as expected?

**Comment by myuseraccount** [comment]
So, is it supposed to remember the toggle I selected for "Extract only URL" the last time I shared a URL to the app?  Because I just did the following:

1. sent link from email to URL cleaner using share function
2. toggled "extract only URL" to on
3. sent a second link, from browser, using share to URL cleaner
4. "extract only URL" was observed to be toggled off

**Comment by svenjacobs** [comment]
@myuseraccount This issue is about remembering the toggle states, that's correct. Unfortunately it has not been implemented yet.

**Comment by svenjacobs** [comment]
This has been resolved and will be available in the next release.

**Comment by myuseraccount** [comment]
Thank you!  The app works great, this will just make it slightly fewer steps to get the result I want.
