### ISSUE TITLE
"Forget" button (a clipboard cleaner) within Leon

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#204]
I already have this feature but I have to go back to the home and press a button out there (a lot of effort). 🤣

It would be convenient to have this function inside Leon.

What do you think about it, Sven?
Might it be helpful?

Just an example (open source)

https://github.com/x13a/Clipeus

**Comment by svenjacobs** [comment]
Hm, I don't think this should be a feature of Leon, because Leon is a URL cleaner. As you have already mentioned there are separate apps for this functionality.
