### ISSUE TITLE
9to5 link support

### ISSUE THREAD

**Issue by vrindavan** [svenjacobs/leon#205]
Original: https://9to5google.com/2023/07/16/google-pixel-nothing-phone-software/?s=09

After cleaning: https://9to5google.com/2023/07/16/google-pixel-nothing-phone-software/

Turns out this is actually Twitter messing up by adding the s param. If I open this in a custom tab on Twitter then it adds the s parameter. Not sure if I should just close this issue then.

**Comment by svenjacobs** [comment]
Hello @vrindavan,

would you like to create a PR for this? 😃

**Comment by vrindavan** [comment]
Not sure if this needs one. I tried disabling the in-app browser for Twitter App and tried on the web. The parameter is not appearing now.

**Comment by svenjacobs** [comment]
It seems Twitter's in-app browser adds these parameters, not 9to5. So I will close this issue.
