### ISSUE TITLE
Leon's home doesn't fit properly my phone screen size

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#208]
Android 13
OnePlus CPH2399
Leon 31

![1000035267](https://github.com/svenjacobs/leon/assets/113377431/56eb8861-cc6a-4ec8-af3e-ea7c63190fae)

![1000035269](https://github.com/svenjacobs/leon/assets/113377431/269e7afa-db16-43ae-a917-5cfd1110c16f)

**Comment by svenjacobs** [comment]
Hello, thanks for the bug report. Did you increase the font size in the OS settings?

**Comment by svenjacobs** [comment]
> > Hello, thanks for the bug report. Did you increase the font size in the OS settings?
> 
> I didn't this, sorry. My fear is doing that I modify other apps with similar issues, already solved. I will try.

The reason why I ask is because it seems the font is very large?

**Comment by svenjacobs** [comment]
The UI should also work with large fonts so yes, this is a bug.

**Comment by svenjacobs** [comment]
@serrq This was fixed and will be available in the next release
