### ISSUE TITLE
AT Internet analytics parameters

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#219]
Original Url

https://www.tagesschau.de/ausland/europa/toto-cutugno-tot-100.html?at_medium=mastodon&at_campaign=tagesschau.de

Manually cleaned by me

https://www.tagesschau.de/ausland/europa/toto-cutugno-tot-100.html

**Comment by svenjacobs** [comment]
Thanks for this feature request. It seems the `at_*` parameters are coming from an [analytics framework](https://developers.atinternet-solutions.com/as2-tagging-en/javascript-en/campaigns-javascript-en/marketing-campaigns-v2/) so we could create a generic sanitizer for these parameters that works on all sites.

**Comment by svenjacobs** [comment]
> Can’t you directly hit the '?' parameter and delete everything that comes next? Would be the wrong approach?

We could do this but then we only have a specific sanitizer for tagesschau.de and not a generic sanitizer for all sites that use this analytics framework.

**Comment by svenjacobs** [comment]
@all-contributors please add @serrq for ideas
