### ISSUE TITLE
Do not remove regular Youtube search params

### ISSUE THREAD

**Issue by Glitchy-Tozier** [svenjacobs/leon#222]
See attached screenshot. The URL I used is this:
```
https://m.youtube.com/results?sp=mAEA&search_query=funny+dog+video
```
No idea what that `sp=mAEA` thing is, but `search_query=funny+dog+video` should probably not get removed.

![Screenshot_20230830-173304_URL Cleaner.jpg](https://github.com/svenjacobs/leon/assets/59611881/61ff8fb6-7a61-49a8-9272-ef8a2ef56bb8)

**Comment by svenjacobs** [comment]
Thanks for the bug report. Currently the YT sanitizer is optimized for video URLs. We need to also take the `result` URL into account.

**Comment by svenjacobs** [comment]
@all-contributors please add @Glitchy-Tozier for bug
