### ISSUE TITLE
Amazon — `tag`/`ascsubtag` tracking parameters not removed

### ISSUE THREAD

**Issue by devnoname120** [svenjacobs/leon#224]
**Input:**
```
https://www.amazon.fr/gp/product/B0C9JKKL7N?tag=egcdealabs08-21&ascsubtag=1498016995
```

**Expected:**
```
https://www.amazon.fr/gp/product/B0C9JKKL7N
```

**Actual:**
```
https://www.amazon.fr/gp/product/B0C9JKKL7N?tag=egcdealabs08-21&ascsubtag=1498016995
```

**Comment by svenjacobs** [comment]
Hello, thanks for the bug report. `/gp/product/` must be a different kind of link because currently we only handle `/dp/` links, like `https://www.amazon.fr/dp/B0C9JKKL7N`. Where did you find this link because when I browse products on `amazon.fr` I only see `/dp/` links.

**Comment by devnoname120** [comment]
@svenjacobs It's an affiliate link that opens when you click on « Voir le deal » from this page: https://www.dealabs.com/bons-plans/hub-usb-c-baseus-7-en-1-1x-hdmi-4k-at-60hz-1x-pd-100w-3x-usb-a-30-5gbps-2x-lecteurs-cartes-sdtf-compatible-pc-macbook-vt-2616385

**Comment by svenjacobs** [comment]
@all-contributors please add @devnoname120 for bug
