### ISSUE TITLE
URL scanner with Virus Total (or other online engines)

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#225]
Knowing what’s behind a link before you opening it.

I guess this feature requires "full internet" permission.

![1000040365](https://github.com/svenjacobs/leon/assets/113377431/10ce3c6c-d850-4cfd-b647-ac8e7e7e1f51)

**Comment by svenjacobs** [comment]
As you have guessed Leon would require the Internet permission and perform network requests.

It is a conscious decision that Leon does not perform any network requests and should just work locally on the device. Please also see [this discussion](https://github.com/svenjacobs/leon/discussions/80).

Hence I'm closing this feature request.

**Comment by svenjacobs** [comment]
Apart from the Internet permission I don't think a Virus Total check should be a functionality of Leon.
As I have mentioned in [other issues](https://github.com/svenjacobs/leon/issues/204#issuecomment-1634175006) I really don't want to overload Leon with functionality outside of it's main purpose.
