### ISSUE TITLE
Support for x.com links

### ISSUE THREAD

**Issue by vjrj** [svenjacobs/leon#232]
Leon should support the new x.com (ex twitter) links. ![Screenshot_2023-09-09-22-19-25-587_com.miui.screenshot-edit.jpg](https://github.com/svenjacobs/leon/assets/180085/5adf4ce1-faaf-4dd1-a6ca-b2760a55228b)

Thanks!

**Comment by svenjacobs** [comment]
@vjrj This was fixed and will be available in the next release

**Comment by vjrj** [comment]
Thanks indeed @svenjacobs for your work

**Comment by vjrj** [comment]
I've just upgraded Leon and it works as expected. Thanks again

**Comment by svenjacobs** [comment]
@all-contributors please add @vjrj for bug
