### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#248]
Please add direct cryptocurrency addresses within the app. I don't want going around to websites.

TRX, LTC, BTC, XEC, SOL, BCH, ALGO, XTZ, DASH, XMR addresses available for donations.

**Comment by svenjacobs** [comment]
Thanks for your feedback. I need think about this. There are various options for donations / sponsoring like [Buy Me a Coffee](https://www.buymeacoffee.com/), [Patreon](https://www.patreon.com/), [GitHub Sponsors](https://github.com/sponsors) etc.

**Comment by svenjacobs** [comment]
> BTC address that begin with 1K? Never seen! What pattern use? BIP86 Taproot is bc1q...

This is an "receiving" address from my [Electrum wallet](https://electrum.org/).

**Comment by svenjacobs** [comment]
Alright, then let's try this SOL address: `3U3gv8dDmhTJP8Htoy67FxSQtT7n5jcMPsnq4i3Nrzwn`

**Comment by svenjacobs** [comment]
Thank you, I got the SOL!

> Is that a random address or fixed? If it is fixed I can add it to my payment addresses book.

To be honest I don't know. I'm not yet familiar with Unstoppable Wallet. This is the address that was shown when I clicked **SOL -> Receive**.

**Comment by svenjacobs** [comment]
> Don't forget to include all your crypto addresses in next Leon version.

I gave this some thought and although I initiated the project and did most of the work so far, this is an open source project which accepts code contributions. A few developers already provided new features, bug fixes or ideas and it wouldn't be fair if only I receive monetary donations. At the moment I don't now what a fair solution would be but for now I will close this issue 😉
