### ISSUE TITLE
Feature request: a Material Design icon.

### ISSUE THREAD

**Issue by Gojikovi** [svenjacobs/leon#255]
Hi there! Could you please add a Material You icon for the app?

**Comment by svenjacobs** [comment]
Hi, thanks for the feedback. We already support [Adaptive Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) but we're missing the monochrome layer, which should be easy to add.

**Comment by Gojikovi** [comment]
> Hi, thanks for the feedback. We already support [Adaptive Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) but we're missing the monochrome layer, which should be easy to add.

Got it, thank you!!

**Comment by svenjacobs** [comment]
This was fixed and will be available in the next release

**Comment by svenjacobs** [comment]
@all-contributors please add @Gojikovi for ideas
