### ISSUE TITLE
Fix bug request: some part of Dark Theme and Dynamic Color don't work.

### ISSUE THREAD

**Issue by ratatouille100** [svenjacobs/leon#257]
### Hi, I've found a bug, Dark Theme and Dynamic Color don't work in "**Sanitizer**" and "**Licenses**" in **Settings**. 
If you open these options, Light Theme will be enabled regardless of what theme is enabled on the system.

[Video](https://github.com/svenjacobs/leon/assets/146064808/cd9abbb7-3115-4395-93aa-a07f2173a469)

## My device:
- Samsung Galaxy A51 4G
- LineageOS 20
- The app version is 33
- [logcat.txt](https://github.com/svenjacobs/leon/files/12726667/logcat.txt)

**Comment by svenjacobs** [comment]
Thanks for this detailed bug report!
This has been already fixed and will be available in the next release.

**Comment by svenjacobs** [comment]
@all-contributors please add @ratatouille100 for bug
