### ISSUE TITLE
Feature Request: Yahoo support

### ISSUE THREAD

**Issue by ratatouille100** [svenjacobs/leon#279]
Please, add support for the Yahoo Search.
![Screenshot_20230926-155329_URL Cleaner.png](https://github.com/svenjacobs/leon/assets/146064808/d62138bf-2fb7-4291-ac08-d536e4067b4b)

It should be
https://search.yahoo.com/search?p=hi

**Comment by svenjacobs** [comment]
Thanks for the feature request. Leon already has a sanitizer for Yahoo but it's for Yahoo search result links, not for the actual query link. So we need to adjust the existing sanitizer or create a new one.
