### ISSUE TITLE
📋 Automatically sanitize URLs in the clipboard

### ISSUE THREAD

**Issue by devnoname120** [svenjacobs/leon#297]
It would be very convenient if Léon could monitor the clipboard in the background, automatically sanitize any URLs that are copied and update the clipboard accordingly.

It would be really convenient to transparently copy URLs from anywhere rather than having to use the share function — which is some apps just don't provide — and find Léon in the long list of apps.

**Comment by svenjacobs** [comment]
I agree with @serrq and I'm not sure if constantly monitoring the clipboard in the background is even technically possible with Android apps.

**Comment by devnoname120** [comment]
I haven't dug into it yet but according to ChatGPT it is. See below the answer of ChatGPT:

-----

> Is it possible to monitor the clipboard in the background on Android using Kotlin? My use case is monitoring the clipboard and transparently remove trackers from URLs that are copied.

Yes, it is possible to monitor the clipboard in the background on Android using Kotlin. You can achieve this by creating a background service or using the `ClipboardManager` API. Here's a high-level overview of how you can approach this:

1. Create a Background Service:
   - Create a background service in your Android app that runs continuously or periodically to monitor the clipboard.

2. Register Clipboard Listener:
   - In your service, register a clipboard listener using the `ClipboardManager` to be notified whenever something is copied to the clipboard.

3. Check for URLs and Remove Trackers:
   - When the clipboard listener is triggered, you can access the copied text and check if it's a URL.
   - If it is a URL, you can parse it to identify and remove any tracking parameters or elements transparently.

4. Modify Clipboard Content:
   - After removing the trackers, you can set the modified content back to the clipboard so that the user pastes the cleaned URL.

Here's a simplified example of how you can register a clipboard listener in Kotlin:

```kotlin
val clipboardManager = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
clipboardManager.addPrimaryClipChangedListener {
    val clipData = clipboardManager.primaryClip
    val copiedText = clipData?.getItemAt(0)?.text.toString()

    // Check if copiedText is a URL and remove trackers if needed
    if (isURL(copiedText)) {
        val cleanedURL = removeTrackers(copiedText)
        val newClipData = ClipData.newPlainText("Label", cleanedURL)
        clipboardManager.setPrimaryClip(newClipData)
    }
}
```

Please note that running a continuous background service may impact device performance and battery life, so it's important to implement this feature responsibly and consider user privacy and permissions. Also, URL parsing and tracking parameter removal can be complex, so you'll need to design this part carefully to handle various URL formats and tracking mechanisms.

**Comment by devnoname120** [comment]
@svenjacobs To be confirmed but I think that it should be possible by issuing OP_READ_CLIPBOARD AppOps commands through Shizuku. This would require users to manually accept the Shizuku dialog that asks them if they want to grant the permissions to Leon.

Would you be hypothetically be open for a PR that offers users this possibility but is optional? A Shizuku dialog would appear and it can't be bypassed by Leon which makes it secure (users can deny it if they want).

**Comment by devnoname120** [comment]
@serrq Does it address your concerns to have Shizuku show a popup to grant permissions to Leon? It would be optional and the feature would be disabled if Shizuku isn't installed (because it's needed to for this feature).

**Comment by svenjacobs** [comment]
To be honest I never heard of Shizuku before 😅 

> Would you be hypothetically be open for a PR that offers users this possibility but is optional? The Shizuku permission dialog would only appear if Shizuku is available and it's secure because it's opt-in and Leon can't bypass it.

Please, I'm fine with a PR. The feature should be optional and should not interfere with users that don't have Shizuku installed. But even if Shizuku is installed the feature should be opt-in via the application settings.

**Comment by devnoname120** [comment]
@serrq I mean the point is that you don't need to install Shizuku at all, and in that case the clipboard monitoring feature would be entirely disabled.

**Comment by svenjacobs** [comment]
@devnoname120 Just to be clear, Shizuku itself requires root privileges, right?

**Comment by devnoname120** [comment]
@svenjacobs No, it can also work over ADB. In that case a user needs to enable adb debugging in the developer settings of Android and grant Shizuku access to it. Shizuku then runs some kind of local proxy in order to issue commands to ADB. 

There are less features when it's used over ADB rather than root, I'm not sure whether the clipboard stuff will work just fine with Shizuku over ADB or if it will require Shizuku to be configured with root. Either way this feature will just be disabled if Shizuku is not available, or if the user clicks on Deny on the dialog that will popup when opening the app for the first time.

**Comment by svenjacobs** [comment]
Alright, I'm looking forward to the PR 🤓

**Comment by devnoname120** [comment]
@svenjacobs Could you assign this issue to me? It would make sure that it doesn't fall off my radar. :)
I don't have a specific ETA for the pull request, my schedule is pretty busy atm so I will work on it when my schedule (and my other open-source projects) allow.

**Comment by svenjacobs** [comment]
@serrq If you don't install Shizuku nothing will change for you. We're going to make sure that this feature is non-intrusive for users that don't need or want it.

**Comment by svenjacobs** [comment]
@devnoname120 Does it mean you will not work on a Shizuku integration for Leon anymore?

**Comment by devnoname120** [comment]
@svenjacobs Yes, you can unassign me (and possibly close the issue).

**Comment by svenjacobs** [comment]
@devnoname120 That's unfortunate but I understand 😢
