### ISSUE TITLE
Not removed parameter (geox.com)

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#302]
Partially cleaned:

https://www.geox.com/it-IT/uomo/scarpe/stivaletti/?sfmc_activityid=a5542c58-11be-4f33-8dd5-5e0ebeae30f2

Manually cleaned:

https://www.geox.com/it-IT/uomo/scarpe/stivaletti/

![1000093039](https://github.com/svenjacobs/leon/assets/113377431/855e72ca-9020-4ad6-98f0-01a57b165109)

**Comment by svenjacobs** [comment]
New sanitizers are currently blocked because I'm [rewriting the internals](https://github.com/svenjacobs/leon/discussions/315) of Leon.

**Comment by svenjacobs** [comment]
Since refactoring still takes a while, I would be happy about a PR.
