### ISSUE TITLE
Google AMP parameters not removed

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#307]
Original URL:

https://amp.latinatoday.it/cronaca/latina-bilancio-operazione-alto-impatto-21-ottobre-2023.html#amp_tf=Da%20%251%24s?aoh=16980098673468&csi=0&referrer=https%3A%2F%2Fwww.google.com

Manually cleaned:

https://www.latinatoday.it/cronaca/latina-bilancio-operazione-alto-impatto-21-ottobre-2023.html

![1000094353](https://github.com/svenjacobs/leon/assets/113377431/62aaf1be-3f7f-4989-886c-f1ddf049c77c)

**Comment by svenjacobs** [comment]
> Have you some idea to solve this issue?

No, as I mentioned in the previous answer various methods must be applied to determine the original URL. Please use tools like [AmputatorBot](https://github.com/KilledMufasa/AmputatorBot) for that 😃
