### ISSUE TITLE
Google Store Url not cleaned

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#308]
Original:

https://store.google.com/gb/product/chromecast_google_tv?hl=en-GB&selections=eyJwcm9kdWN0RmFtaWx5IjoiWTJoeWIyMWxZMkZ6ZEY5bmIyOW5iR1ZmZEhZPSIsImhlcm9Qcm9kdWN0cyI6W1siY0hKa1h6YzRNekpmTXprMU1nPT0iLDEsbnVsbF1dfQ%3D%3D

Manually cleaned:

https://store.google.com/gb/product/chromecast_google_tv

**Comment by svenjacobs** [comment]
New sanitizers are currently blocked because I'm [rewriting the internals](https://github.com/svenjacobs/leon/discussions/315) of Leon.

**Comment by svenjacobs** [comment]
Since refactoring still takes a while, I would be happy about a PR.
