### ISSUE TITLE
Feature request: Add support to archive services

### ISSUE THREAD

**Issue by bangzek** [svenjacobs/leon#31]
Can't you add another URL related feature into the app?

Add support to prepend archive.is or wayback machine to the url so I can easily access those service from the app.

**Comment by svenjacobs** [comment]
Hello Zakaria,

thanks for your feedback. I appreciate your idea however I think that it doesn't fit into the main purpose of Leon. Leon's purpose is to remove tracking parameters from URLs before sharing. Your idea rather sounds like a new app? I hope you understand my decision.

Kind regards.
