### ISSUE TITLE
Another parameter (path)

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#313]
Original URL:

https://mail.dmail.ai/login?path=%2Finbox

Manually cleaned:

https://mail.dmail.ai/login

**Comment by svenjacobs** [comment]
I don't think this is a tracking parameter. It probably opens this path sister login. Leon should only remove tracking / advertising parameters.

**Comment by svenjacobs** [comment]
I'm sorry but Leon is primarily for tracking parameters.
