### ISSUE TITLE
Incorrectly cleans URL's of YouTube playlists

### ISSUE THREAD

**Issue by JohnReedLOL** [svenjacobs/leon#329]
**Note:** I am on the most recent version of this app, Version 36 from F-Droid added on 11/5/2023.

**Bug report:**

When I use the YouTube app on my phone I sometimes share playlists. The URL for a YouTube playlist I wanted to share was 
[https://youtube.com/playlist?list=PLkqz3S84Tw-QYEdfTLBzxJ1FAprtqeEpJ&si=2tDDmSKejG2GTtj5](https://youtube.com/playlist?list=PLkqz3S84Tw-QYEdfTLBzxJ1FAprtqeEpJ&si=2tDDmSKejG2GTtj5) 
 
I put that URL into the app and after cleaning it shortened the URL to 
[https://youtube.com/playlist](https://youtube.com/playlist)
 
See screenshot:

![Screenshot_20231129-102334](https://github.com/svenjacobs/leon/assets/5510392/d2c21218-2a5a-46ed-89c4-43494fb040ef)

That shortened URL does not contain the parameter that specifies which playlist in YouTube to GET. The correct shortened URL is actually 
[https://youtube.com/playlist?list=PLkqz3S84Tw-QYEdfTLBzxJ1FAprtqeEpJ](https://youtube.com/playlist?list=PLkqz3S84Tw-QYEdfTLBzxJ1FAprtqeEpJ)

I tried it out with other YouTube playlists, the same thing happens. 

Please fix,

- user JohnReedLOL

**Comment by svenjacobs** [comment]
@JohnReedLOL Thanks for the report. This has been fixed and will be available in the next version.

**Comment by svenjacobs** [comment]
@all-contributors please add @JohnReedLOL for bug
