### ISSUE TITLE
Instagram links don't get cleaned anymore

### ISSUE THREAD

**Issue by rhubarbzed** [svenjacobs/leon#336]
Links for instagram used to be cleaned successfully but now don't.
Tried turning on and off sanitizers and clearing cache / app data to no avail.

Example links;
https://www.instagram.com/reel/_inserttext_/?igsh=ugWUgfb
https://www.instagram.com/p/_inserttext_/?igsh=ugWUgfb

- "?igsh=" used to be removed
- now it stays there
- decode URL and extract only do not change anything

**Comment by svenjacobs** [comment]
@all-contributors please add @rhubarbzed for bug
