### ISSUE TITLE
Make the URL text selectable on the main screen

### ISSUE THREAD

**Issue by JonathanBaby** [svenjacobs/leon#349]
Hello Sven and contributors,

It could be handy to make the URL text selectable on the main screen. In case of no sanitizers available, it would still be possible to select any part of the URL root manually, through the default text selection controls : [Text selection with touch control (Material Design Guidelines)](https://m3.material.io/foundations/interaction/inputs#bb101c84-f853-492d-8754-1e6176221abf) (long press + highlight the text to select, using handles).

This would stick to a simple [TextView](https://developer.android.com/reference/android/widget/TextView) component, but **selectable**.
This would be a smaller change than #189 which requires to switch to an **editable** [text input field](https://m3.material.io/components/text-fields/overview), which would need an [EditText](https://developer.android.com/reference/android/widget/EditText) component.

My support and thanks for the great work :+1:

**Comment by svenjacobs** [comment]
Thanks for the feature request. This was easy to resolve and will be available in the next release.

**Comment by svenjacobs** [comment]
@all-contributors please add @JonathanBaby for ideas
