### ISSUE TITLE
Mydealz.de URL Cleaner

### ISSUE THREAD

**Issue by farOverNinethousand** [svenjacobs/leon#358]
German deal portal mydealz.de is using special links in their app which when used on desktop and/or devices without their app will do multiple redirects until the final destination is reached.
Afaik this also means that non-app-users cannot use the URLs shared from MyDealz app users.
However there is a trick to avoid this.

Example of the "bad" URL:
`https://www.mydealz.de/share-deal-from-app/2117879`
Example of a "good" URL:
`https://www.mydealz.de/deals/xbox-series-x-ca-360eur-durch-guthaben-50eur-psn-ca-33eur-uvm-visa-kreditkarte-erforderlich-wechselkurs-ars-zu-eur-2117879`

**How to change the bad URL to a "good" one:**
`https://mydealz.de/diskussion/a-2117879`
Alternative:
`https://www.mydealz.de/deals/a-2117879`
Those links will directly redirect to the final destination without the advertisement/tracking-redirects.

The letter a in the examples  can be replaced by any random string.
**EDIT**

They also got other portals so the following domains should maybe also be included:

- mydealz.de
- promodescuentos.com
- pelando.com.br
- hotukdeals.com
- nl.pepper.com
- pepper.pl
- preisjaeger.at
- dealabs.com
- chollometro.com
- pepper.it
- desidime.com
- pepper.ru

**Comment by farOverNinethousand** [comment]
* I know this request is locked by [your code rewrite](https://github.com/svenjacobs/leon/discussions/315) but I was unable to set the appropriate labels myself.

**Comment by svenjacobs** [comment]
Thanks for the feature request 😃

**Comment by farOverNinethousand** [comment]
Addendum:
Besides those trackingURLs, their "normal" URLs can now also contain tracking parameters.
Example:
`https://www.mydealz.de/diskussion/gratis-adidas-fussball-trikot-2383743?pprmrkntfctnsrd=123456789&UATypeId=18`

**Comment by svenjacobs** [comment]
Since refactoring still takes a while, I would be happy about a PR.
