### ISSUE TITLE
"Open" functionality not working when Leon is default browser

### ISSUE THREAD

**Issue by whizzzkid** [svenjacobs/leon#372]
When using leon as the default url-opener, the open action doesn't open anything (because the app is already open). I can share it on the browser, but if it allowed me to issue intent to open the URL by default, that would be sweet!

I've been using https://github.com/johnste/finicky for a while, which allows me to define different browser/profiles to open different url patterns. That makes my life so much easier, if I can do something similar (override the verified-links feature in android) it would be sooo good! 🙏🏽

**Comment by svenjacobs** [comment]
Regarding your first point, would it help if Leon opened URLs in a custom tab (see #346)?

**Comment by svenjacobs** [comment]
This is interesting:

Leon uses [Intent.createChooser()](https://developer.android.com/reference/android/content/Intent#createChooser(android.content.Intent,%20java.lang.CharSequence)). The documentation of [ACTION_CHOOSER](https://developer.android.com/reference/android/content/Intent#ACTION_CHOOSER) states

> all possible activities will always be shown even if one of them is currently marked as the preferred activity

However it seems some Android version has changed the behavior and always opens the default browser, even if `createChooser()` is used. I need to investigate further...

**Comment by svenjacobs** [comment]
[Reddit thread](https://www.reddit.com/r/AndroidQuestions/comments/o3l0by/suddenly_forced_to_have_default_browser_app/) about default browser on Android.

**Comment by svenjacobs** [comment]
[Bypass default app for any Intent](https://matteinn.com/posts/bypass-default-app-for-any-intent/)

**Comment by UsamaKarim** [comment]
It seems I landed in the right place after searching exactly similar app for quite some time.

**Comment by svenjacobs** [comment]
> It seems I landed in the right place after searching exactly similar app for quite some time.

@UsamaKarim Thanks for your feedback 🫶🏼 but please use [discussions](https://github.com/svenjacobs/leon/discussions) for that 🙂

**Comment by svenjacobs** [comment]
Even when trying to manually query all applications that can fulfill a browser `Intent`, the result will only list the default browser, even when multiple browsers are installed.

```kotlin
val intent = Intent(Intent.ACTION_VIEW, Uri.parse("http://"))
// OR 
// val intent = Intent(Intent.ACTION_MAIN).apply {
//   addCategory(Intent.CATEGORY_APP_BROWSER)
// }

// Contains only a single result
val activities = context.packageManager.queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY)
```

It seems newer Android versions just don't allow to get all browsers 😞 

**The only solution I see so far is to not set a default browser on the device.** Then the chooser should open.
