### ISSUE TITLE
Please keep music.youtube.com links as YouTube Music links

### ISSUE THREAD

**Issue by Mikaela** [svenjacobs/leon#377]
#98 and #137 introduce removing the `music.` subdomain, but this breaks opening the link in the YouTube Music app as it will open in regular YouTube instead and introduces new issues:

- YouTube Music customers with a cheaper plan will then see ads on YouTube.
- The video is autogenerated based on the YouTube Music track rather than the music video (which would be a separate tab in YouTube Music) so in my opinion the new link is pointless.
- Some YouTube Music tracks are only restricted to paid YouTube Music plans which again breaks the links. I don't have an example at hand right now as I have had a plan for ages, but my friends have complained to me about it sometimes.

I have noticed that I can remove the YouTube Music sanitizer from settings, but that again keeps the share ID in the link and while I am used to removing it by hand at this point, I was recently pointed out that pasting it to an app which has URL previews will tell Google that the link has been used at least once (even if by a chat app server).

**Comment by svenjacobs** [comment]
Hello @Mikaela,

thanks for the bug report. Can you please post a full example of a `music.youtube.com` link?
What are your expectations? To only remove the share ID?

**Comment by Mikaela** [comment]
Example link: https://music.youtube.com/watch?v=KGFkMD2zotU&si=JrZ7QzX4VeMrfzp8

Expected result: https://music.youtube.com/watch?v=KGFkMD2zotU (share ID removed)

-----

> ...the music video (which would be a separate tab in YouTube Music) so in my opinion the new link is pointless.

For the previous links this would be:

- Unprocessed: https://music.youtube.com/watch?v=U-b5gDWVnps&si=cIZRNZY0LpiQnp8Y
- Result: https://music.youtube.com/watch?v=U-b5gDWVnps (share ID removed)

And as this would be actual video, I wouldn't mind that much if the `music.` subdomain was dropped, even if I would consider it as unexpected behaviour.

However I have no idea how would an external app without any APIs make the conversion and I think the user would share a video if they wanted to share a video instead of just the song from the first two links.

**Comment by svenjacobs** [comment]
Leon contains multiple sanitizers for YouTube. As you already found out there is the sanitizer for [YT Music](https://github.com/svenjacobs/leon/blob/main/core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeMusicSanitizer.kt), which converts the URL into a regular YT URL. But there is also the generic YT sanitizer which removes unwanted parameters. The only problem I see is that the generic YT sanitizer [doesn't handle](https://github.com/svenjacobs/leon/blob/main/core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/youtube/YoutubeSanitizer.kt#L40) `music.youtube.com` at the moment.

So if I would fix the generic YT sanitizer and you disable the YT Music sanitizer, it should be the desired outcome?

**Comment by svenjacobs** [comment]
> No, it wouldn't hurt me as the sanitizers are trivial enough to disable and I assume the settings persist requiring it to be toggled only once per service.

That's correct. The setting will be persisted.

**Comment by svenjacobs** [comment]
This is now available in v39.

**Comment by Mikaela** [comment]
Thsnk you, it works as expected

**Comment by svenjacobs** [comment]
@all-contributors please add @Mikaela for bug
