### ISSUE TITLE
Please try to add support for Flipkart URL's

### ISSUE THREAD

**Issue by jaswinder77** [svenjacobs/leon#39]
Please try to add support for Flipkart URL's too.

Example URL:
https://www.flipkart.com/msi-gf63-thin-core-i5-10th-gen-8-gb-512-gb-ssd-windows-10-home-4-graphics-nvidia-geforce-rtx-3050-144-hz-10uc-607in-gaming-laptop/p/itm92565651dc3ed?pid=COMG5AWT9CKRMEFU&lid=LSTCOMG5AWT9CKRMEFULV38QB&marketplace=FLIPKART&q=gaming+laptop&store=6bo%2Fb5g&srno=s_1_15&otracker=AS_QueryStore_OrganicAutoSuggest_1_9_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_9_na_na_na&fm=SEARCH&iid=22ff2dee-d44e-40e3-9811-5d229fa974fc.COMG5AWT9CKRMEFU.SEARCH&ppt=hp&ppn=homepage&ssid=zv1f42w4bs3azitc1635436210945&qH=da5ee6f53d84b3c2

**Comment by svenjacobs** [comment]
Hello @jaswinder77, sorry for the late reply.

I'm not familiar with Flipkart. What parameters can actually be removed from the address above without breaking the site?

**Comment by jaswinder77** [comment]
> Hello @jaswinder77, sorry for the late reply.
> 
> I'm not familiar with Flipkart. What parameters can actually be removed from the address above without breaking the site?

I am not sure about other cases, but in the case of above URL, none of the parameters seem to be absolutely required while sharing the product with someone. 🤔 

The URL without parameters seems good enough:

https://www.flipkart.com/msi-gf63-thin-core-i5-10th-gen-8-gb-512-gb-ssd-windows-10-home-4-graphics-nvidia-geforce-rtx-3050-144-hz-10uc-607in-gaming-laptop/p/itm92565651dc3ed

**Comment by rsb-23** [comment]
everything after ? can be removed for Flipkart

**Comment by svenjacobs** [comment]
Thanks for your patience. A sanitizer for flipkart.com has been added to version 0.8.0 which should be available in Play Store and F-Droid soon.
