### ISSUE TITLE
Remove twitter ?s= tracking

### ISSUE THREAD

**Issue by Donnnno** [svenjacobs/leon#40]
Hi! 
Great app :)

I noticed that the URL sanitizer doesn't remove the `?s=` part from a twitter link when you share it.

You can find a more detailed description here: 
https://twitter.com/_adryd/status/1429661064887738375

**Comment by svenjacobs** [comment]
Hi @Donnnno,

thanks for your feedback 😃 That's really weird because a sanitizer for Twitter has been added in version [0.6.0](https://github.com/svenjacobs/leon/blob/main/CHANGELOG.md). What version of Leon are you using? Can you please post the Tweet URL which is not working?

**Comment by Donnnno** [comment]
Oh, never mind! It removes them now. Idk maybe I was using it too fast or something last time. Thanks!
