### ISSUE TITLE
retain #anchors when cleaning URL

### ISSUE THREAD

**Issue by slootsky** [svenjacobs/leon#41]
after cleaning a URL today, I noticed that the #anchor was also removed.  If this could be retained, that would be ideal

**Comment by slootsky** [comment]
will do.  (I need to find it again)

I think the fix is on line 55 of SanitizerStrategy.kt

change
        val regex = Regex("[?&]${sanitizer.name}=.[^&]*")
to
        val regex = Regex("[?&]${sanitizer.name}=.[^&#]*")

But I don't have the capability of compiling or testing that fix.

**Comment by slootsky** [comment]
Since this link identifies my city, I'll delete this comment after you acknowledge it.

https://www.ottawapublichealth.ca/en/shared-content/assessment-centres.aspx?utm_source=Friendly_URL&utm_medium=Antiviral_Friendly_URL&utm_campaign=Coronavirus#antiviral

**Comment by slootsky** [comment]
Here is a generic example URL

https://www.example.org/en/shared-content/assessment-centres.aspx?utm_source=Friendly_URL&utm_medium=Antiviral_Friendly_URL&utm_campaign=Coronavirus#antiviral

**Comment by svenjacobs** [comment]
> Since this link identifies my city, I'll delete this comment after you acknowledge it.

Thanks, got the link.

**Comment by svenjacobs** [comment]
This has been fixed in version 0.7.1 which should be available on F-Droid and Play Store soon. Thanks for your feedback 😃
