### ISSUE TITLE
Sanitizer for Search Engine Links

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#42]
When using a search engine, the results links are often garbaged w/ tracking info.  It'd be amazing if Léon could handle these, too.

Examples when searching `léon url cleaner`  & choosing link to this repo:
- [ ] Google: https://www.google.com/url?q=https://github.com/svenjacobs/leon&sa=U&ved=2ahUKEwiB2f7ZqJr3AhVMjYkEHQ-DC6gQFnoECAEQAg&usg=AOvVaw2u8hlrT4OUF1_m1GnmhVAy

- [x] Yahoo!: https://r.search.yahoo.com/_ylt=A0geKLovoVtisIEAUapx.9w4;_ylu=Y29sbwNiZjEEcG9zAzQEdnRpZAMEc2VjA3Ny/RV=2/RE=1650201007/RO=10/RU=https%3a%2f%2fgithub.com%2fsvenjacobs%2fleon/RK=2/RS=rHoItccMzwyZAXsJuDMkBaKUMx0-

- [x] AOL: https://search.aol.com/click/_ylt=A0geK.HAoltiwykAlAR8CWVH;_ylu=Y29sbwNiZjEEcG9zAzQEdnRpZAMEc2VjA3Ny/RV=2/RE=1650201408/RO=10/RU=https%3a%2f%2fgithub.com%2fsvenjacobs%2fleon/RK=0/RS=cXRWej4shdsEIIDm147.G4CRZEo-

**Comment by svenjacobs** [comment]
Hi @TPS,

this is doable, sure. Do you have an idea which parameters can be safely removed without breaking the link?

**Comment by TPS** [comment]
For `google.com/url`, the sanitized link needed is the _value_ to the `q` parameter up 'til 1st unescaped `&`— _everything_ else is tracking.

For the other 2, delimit char is `/`, parameter is `RU`, & link needed is its _[percent-decoded](https://en.m.wikipedia.org/wiki/Percent-encoding)_ value up 'til 1st unescaped `/`.  As with the 1st, everything else is garbage.

**Comment by svenjacobs** [comment]
Thinking about this a bit more I wonder, why do you want to clean a URL of a search engine result and not just share / use the actual URL (`https://github.com/svenjacobs/leon` in your examples). Because the search engine links just forward to the acutal site anyway (but leave some nice tracking info at Google, Yahoo, AOL, etc 😉)

**Comment by TPS** [comment]
Because I usually share directly from search engine results page to whatever's my next step.

**Comment by svenjacobs** [comment]
Would it be okay if Leon extracts the actual URL from the link and skips the search engine altogether? For Google this would be just the value of the `q` parameter. For Yahoo and AOL this would be a little more complicated, since the value has to be URL-decoded first. Currently Leon's logic is solely based on regular expressions.

**Comment by TPS** [comment]
Yes, that's exactly what I'm wishing for.

**Comment by svenjacobs** [comment]
Great! This however requires rewriting of some Leon internals since currently all sanitizers are based on the concept of _removing_ parts from a URL. Future sanitizers must be able to _extract_ and _convert_ parts.

**Comment by svenjacobs** [comment]
Sanitizers for Google, Yahoo and AOL have been added to the current development version and will be available in the next release.

**Comment by TPS** [comment]
@svenjacobs The sanitizers for Yahoo & AOL work perfectly, but the simpler sanitizer for Google seems not to do anything, e.g., for the example above.

**Comment by svenjacobs** [comment]
I see the difference. Your Google URL has the actual URL in the `q` parameter but when I developed the feature and tested it, it has the URL in the `url` parameter like

```
https://www.google.com/url?url=https://github.com/svenjacobs/leon
```

I'm unable to produce a link with a `q` parameter. I'm using Google search on mobile. How do you get a link with the `q` parameter?

**Comment by TPS** [comment]
Huh!  I've only just now noticed, but, on Webview browsers (Chrome, Edge, &), your version is what happens.  But I generally use Google search on Firefox, which produces the above.

**Comment by svenjacobs** [comment]
This is interesting. Of course adding both parameters `q` and `url` to the sanitizer should not be a problem.

**Comment by svenjacobs** [comment]
This has been fixed and will be available in the next release.

**Comment by svenjacobs** [comment]
@TPS Please retest with version 1.0.1 which should be available on F-Droid soon. Build already went through.

**Comment by TPS** [comment]
Works perfectly! 🙇🏾‍♂️  Thanks!

Just realized GMail uses a similar, but not identical scheme.  I'll open a new issue for that.
