### ISSUE TITLE
Read URL from clipboard

### ISSUE THREAD

**Issue by Enkidu70** [svenjacobs/leon#43]
## Minimum feature request:
Please implement a solution to make Leon able to read URL from clipboard.
(Only exact URL is stored in clipboard.)

## Maximum feature request:
In addition to min. feature request, make Leon able to filter out URL from clipboard text.
(Text containing an URL is stored in clipboard.)

## Why?
In apps such like Telegram messenger you are often not able to share a link with an external app. You are only able to copy URL to clipboard.

Tnx in advance,
Enkidu

**Comment by MagicRB** [comment]
Can ghis be made automatic? Without opening the Leon app?

**Comment by svenjacobs** [comment]
> Can ghis be made automatic? Without opening the Leon app?

I doubt this is technically possible. This is not how the Android intent mechanism works.

**Comment by TPS** [comment]
While doing this, is it possible for Leon to have an option to <kbd>Copy</kbd>*to* clipboard, when neither<kbd>Share</kbd>nor<kbd>Verify</kbd>will quite do?

**Comment by svenjacobs** [comment]
> While doing this, is it possible for Leon to have an option to <kbd>Copy</kbd> *to* clipboard, when neither <kbd>Share</kbd> nor <kbd>Verify</kbd> will quite do?

Yes, please create a new ticket since "copy to clipboard" is a new feature request 🙂

**Comment by svenjacobs** [comment]
The "import from clipboard" functionality was added to the start screen. Additionally a "extract only URL" functionality was added to the result screen. Both features are available in version 1.0.0 which should be available on F-Droid and Play Store soon.
