### ISSUE TITLE
Remove further unnecessary parameters from URL

### ISSUE THREAD

**Issue by Enkidu70** [svenjacobs/leon#44]
## Minimum feature request:
Please implement a solution to make Leon able remove unnecessary parameters from URLs, like
* empty values
* various session ids (this might also be a privacy feature!) like jsessionid, sessionid, ...

### Exampel URL:
https://www.buch24.de/shopdirekt.cgi?sessionid=1650808921-319962258&id=13241297&p=3&sid=&static=0&nav=
### Real necessary:
https://www.buch24.de/shopdirekt.cgi?id=13241297&p=3&static=0

## Maximum feature request:
In addition to min. feature request, enable the user to add own parameter names to be wiped out.

## Why?
Keep URL short and empower the user to remove unwanted stuff.

Tnx in advance,
Enkidu

**Comment by svenjacobs** [comment]
Sanitizers for generic session IDs and empty parameters have been added to version 0.10.0 which should be available on F-Droid and Play Store soon.
