### ISSUE TITLE
Convert Amazon links to AmazonSmile?

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#45]
@svenjacobs Please add the functionality from [Amazon Smile Redirect](https://github.com/webdevnerdstuff/amazon-smile-redirect) to Léon (e.g., [convert](https://github.com/svenjacobs/leon/issues/42#issuecomment-1141794303) `www.Amazon.[com|co.uk|de]` links to `Smile.Amazon.[com|co.uk|de]`).

_Originally requested in https://github.com/svenjacobs/leon/issues/18#issuecomment-1141568570_

**Comment by svenjacobs** [comment]
The feature is now implemented and will be available in the next release.

**Comment by TPS** [comment]
Small bug w/ this: afaik, only `Amazon.[com|co.uk|de]` are Smile eligible.  I believe the program hasn't been rolled out to _any_ other local Amazon, e.g., `Amazon.Ca`.

**Comment by svenjacobs** [comment]
Good to know. However, do we want to handle this in the URL rewriter? This means maintaining a list of possible Amazon Smile domains which might change anytime. I would prefer if affected users just disable the rewriter in the application settings.

**Comment by TPS** [comment]
I feel like it should be maintained here for these reasons:
- Amazon _rarely_ adds new Smile domains.  This list has been constant for ~5 years.
- When this _does_ rewrite for a non-Smile-capable Amazon domain, the link _breaks_, not just redirecting to the main domain (which, imho, would be trivial for Amazon to do), which they _already_ do when logged-out & trying to access a Smile domain.
