### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by alpeni** [svenjacobs/leon#450]
If you share something from google maps it does one of these two things.

Offline mode: then it shares it as maps.google.com/ (some coordinates here)

Online mode: then it shares it maps.app.goo.gl/SOMECODEHERE  -> with this one can specifically track who shared it to whom. If you repeat this in another phone for same place you get different code.

My suggestion would be if Leon uses some form of https request to find the redirected URL and then share that.

Thanks for the great app.

**Comment by svenjacobs** [comment]
Hello, thanks for your feedback.

However Leon will not perform HTTP requests. The issue has been discussed [here](https://github.com/svenjacobs/leon/discussions/80#discussion-4475589).
