### ISSUE TITLE
Option to Copy to clipboard

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#46]
Please have an option to <kbd>Copy</kbd> *to* clipboard, when neither <kbd>Share</kbd> nor <kbd>Verify</kbd> will quite do.

_Originally posted in https://github.com/svenjacobs/leon/issues/43#issuecomment-1146663239_

**Comment by svenjacobs** [comment]
This has been added to version 0.9.0. As always, should be available on Play Store and F-Droid soon.

**Comment by TPS** [comment]
Thanks very much! 🙇🏿‍♂️
