### ISSUE TITLE
YouTube time markings are removed 

### ISSUE THREAD

**Issue by guerda** [svenjacobs/leon#460]
If you clean a YouTube URL which contains a time mark (?t=<number in seconds>), this time mark will be removed too.

Example: `https://www.youtube.com/live/CK6pE4-8kCg?si=5Y1bV4klawydjKqM&t=17271` becomes `https://www.youtube.com/live/CK6pE4-8kCg` 

It should become `https://www.youtube.com/live/CK6pE4-8kCg?t=17271`

It might be enough to add `t` to this list

```
RegexFactory.exceptParameter("(v|search_query|list)")
```

**Comment by svenjacobs** [comment]
Hello Philip,

thanks for the bug report. Yes, adding `t` should be enough. Do you want to create an PR? 😄

**Comment by guerda** [comment]
Great, thanks for the confirmation. 

I will do once I get to a "big screen" computer 😁
