### ISSUE TITLE
Clean Instagram `igshid` param

### ISSUE THREAD

**Issue by aricooperdavis** [svenjacobs/leon#48]
Instagram adds the `igshid` tracking parameter to links, I.e.

    https://www.instagram.com/p/Ceeg-VgI4yF/?igshid=YmMyMTA2M2Y=

Could Léon support cleaning these too?

**Comment by svenjacobs** [comment]
Thanks for the feature request. I will certainly add this to a future version of Leon 🙂

**Comment by svenjacobs** [comment]
The Instagram sanitizer has been added to version 0.10.0 which should be available on F-Droid and Play Store soon.
