### ISSUE TITLE
Unable to register leon as a browser after the latest update.

### ISSUE THREAD

**Issue by whizzzkid** [svenjacobs/leon#494]
It's on one of my other devices. I disabled updates on my main device. The app does not show up in the default browser settings.

**Comment by svenjacobs** [comment]
> I validated manually by installing APK, last good version was [v43](https://github.com/svenjacobs/leon/releases/tag/v43) 

I think this happened with PR #476. I need to investigate further why this broke the browser functionality 👀 

> but the `Open URLs in browser custom tabs` is still broken.

Can you please create a separate issue for this and describe when this stopped working?

**Comment by svenjacobs** [comment]
The bug with Leon as a browser was fixed.
As mentioned please create another issue for `Open URLs in browser custom tabs`.
