### ISSUE TITLE
(Semi-humorous) feature suggestion: replace tracker code with `[object Object]` instead of removing it

### ISSUE THREAD

**Issue by vladkorotnev** [svenjacobs/leon#501]
Basically what the title says — put in a base64 string of [object Object] instead of the tracker ID rather than removing it.

That way if there is some auditing being done on the tracker logs, the cleaned URLs don't just prevent them from getting data, but also cost the offending party active engineering time to figure out what explodified.

I might get on to doing that myself in a fork and PRing, but sadly this would only work if used en-masse... otherwise I've just got myself a fancy own unique tracking code :-)

**Comment by svenjacobs** [comment]
Hello, honestly I'm not sure what to make of this suggestion. Do we really want to mock and confuse other people?
If we do this, maybe we give those people a reason to actively work against Leon and similar tools? Better not stir up a hornets' nest 😉
