### ISSUE TITLE
YouTu.be should be cleaned like YouTube.Com

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#506]
@svenjacobs I've noticed that, if the [`YouTu.be` → `YouTube.Com` conversion](https://github.com/svenjacobs/leon/issues/56) is _disabled_, e.g. the `si=` parameter isn't cleaned.  Is it possible for `YouTu.be` cleaning to be done _exactly_ like for `YouTube.Com`?  It helps when sharing URLs from the site/app, where URLs are minimized like that.

**Comment by svenjacobs** [comment]
Sure, solved via #507.

**Comment by TPS** [comment]
@svenjacobs Thanks very much! 🙇🏾‍♂️
