### ISSUE TITLE
Always shows "0 parameters removed" 

### ISSUE THREAD

**Issue by slootsky** [svenjacobs/leon#51]
Even when the application removes parameters, it says "0 parameters removed"

**Comment by svenjacobs** [comment]
That's weird. Can you please post an example link where this occurs or even provide a screen recording? However this information will be likely [removed](https://github.com/svenjacobs/leon/issues/50#issuecomment-1157374107) anyway.

**Comment by svenjacobs** [comment]
Closing the issue as the current version 0.10.0 doesn't show this information anymore.
