### ISSUE TITLE
Updated ru (Russian) translation

### ISSUE THREAD

**Issue by chel1k** [svenjacobs/leon#52]
I have translated your application into `ru` (*Russian*). Here is the xml:
https://hastebin.com/kewifuxeji
---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by chel1k** [comment]
https://hastebin.com/posokizuha

**Comment by svenjacobs** [comment]
Thanks for your contribution! I added the translations. They will be available in the next release.
