### ISSUE TITLE
Can this be registered as a browser?

### ISSUE THREAD

**Issue by slootsky** [svenjacobs/leon#55]
Is it possible to make the URL cleaner the target for default browser in Android?

It would be nice to have an this as my default browser (I'm not expecting actual browser behavior) so that it can strip all the tracking junk and then I can copy the URL to the browser myself.

**Comment by svenjacobs** [comment]
Well, I could add an [intent-filter](https://developer.android.com/guide/topics/manifest/intent-filter-element) to the [manifest](https://developer.android.com/guide/topics/manifest/manifest-intro) which handles all HTTP intents. But this would show Leon as a "browser" for every user, which might not be desired. It seems intent filters can be somewhat programmatically enabled / disabled by using an [activity-alias](https://stackoverflow.com/a/46445051/416029), which I never used before. So a bit of investigation is required on my side.

**Comment by TPS** [comment]
Another reason this'd be useful is 1 elects _not_ to have a default browser, so 1 could directly open a URL w/ this & then use <kbd>Verify</kbd> to redirect wherever.

**Comment by svenjacobs** [comment]
This will be available in the next release.

**Comment by svenjacobs** [comment]
This is disabled by default. You'll find a switch to enable this in the app settings. However after enabling it, on newer Android versions you might have to set Leon as the default browser in the OS settings as well.

**Comment by TPS** [comment]
> However after enabling it, on newer Android versions you might have to set Leon as the default browser in the OS settings as well.

If there _is_ no default browser, it'll open up a list of browsers, which should include Léon.  I'll confirm whenever I get to test the F-droid build.

**Comment by svenjacobs** [comment]
Should hopefully be available on F-Droid in a few days.

**Comment by slootsky** [comment]
oh! AWESOME!  THANK YOU
