### ISSUE TITLE
Youtu.be domain+url rewriter 

### ISSUE THREAD

**Issue by slmb3** [svenjacobs/leon#56]
`https://youtu.be/video-id` should be transformed into `https://www.youtube.com/watch?v=video-id`. These youtu.be links comes from the share function.

Thanks for the app!

**Comment by svenjacobs** [comment]
Thanks for your feedback. Usually Leon tries to remove obsolete parameters and reduce the size of URLs. There is one exception to this rule which is the [Amazon Smile](https://github.com/svenjacobs/leon/issues/45) rewriter. But in this particular case the benefit of rewriting the URL is to collect donations for charities.

Why do you want to convert a shorter `youtu.be` link to a longer `youtube.com`?

**Comment by slmb3** [comment]
The short url is specific to the share function and helps google track such. It redirects to 
`https://www.youtube.com/watch?v=video-id&feature=youtu.be` and thus should be sanitized before it can get to that point

**Comment by svenjacobs** [comment]
This will be available in the next release.
