### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by svenjacobs** [svenjacobs/leon#59]
Implement a nice splash screen with [Splash Screen API](https://developer.android.com/guide/topics/ui/splash-screen).

**Comment by TPS** [comment]
Just curious to know why?  Léon loads virtually instantly & gets to the functionality immediately thereafter.  What then would a loading screen accomplish other than slowing down the workflow?

**Comment by svenjacobs** [comment]
Please don't mix up loading and splash screen 😃 On modern Android version, every app has a splash screen. It's the animation that occurs when the app is first started and wasn't in the background anymore. Usually when no explicit splash screen is provided by the app, the default splash screen animates the app icon from where it was launched to full screen until the app was started.

The Splash API provides means to adjust this initial splash screen with a small animation for example.

This would just be a cosmetic change but it has no importance so I will close this issue.
