### ISSUE TITLE
YouTube exit links

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#61]
@svenjacobs YouTube uses a similar, but not identical scheme, to #42.  E.g., on [Google's own About page](https://m.youtube.com/c/google/about) to `About Google`,  YT gives

- `https://www.youtube.com/redirect?event=channel_description&redir_token=QUFFLUhqa1JoZzZUczlhMWJCaTBoc1lqa3ZtX2Rpd0ZPUXxBQ3Jtc0tsYVhpenF1czV5VjlwZm5pemZGdm4zNHVXSldEUlR6dHNhZzI0UkFvLXo0cEVyUk0yaHR5LVhGWEFCLVdzdmlZWGU3eUY5ZWdUZTBUbEw3MVg4UDZCRzdkXzdaaGczT25Ka3Q5bjUzTmxWVHF3Tll6MA&q=http%3A%2F%2Fwww.google.com%2Fabout%2F&html_redirect=1`

which, of course, should just be

- `http://www.google.com/about/`

_(Oops, Google forgot `httpS`?! 🤣  I digress.…)_

So just the url-decoded value of parameter `q`?   This would work great in conjunction w/ #55.

**Comment by svenjacobs** [comment]
Thanks for the feature request. It will be available in the next release.
