### ISSUE TITLE
Option to auto copy to clipboard

### ISSUE THREAD

**Issue by timonsku** [svenjacobs/leon#71]
It would be a nice option if the app could immediately copy to clipboard and close again instantly, going back to the app that was shared from. That way it would closely mimmick a "copy link" that you would otherwise might use directly from the source app.
Afaik its possible to differentiate "app open" from app drawer and from content share, so that the app is still reachable if you open it directly.

**Comment by svenjacobs** [comment]
Hi @timonsku, do I understand this request correctly that you want Leon to instantly parse a link from the clipboard when opened and copy the result into the clipboard, too?

If yes, I would probably create a second `Activity` for this as this is a special behaviour which should not interfere with the standard behaviour.

**Comment by timonsku** [comment]
Yes exactly! And yea that sounds like a good approach.

**Comment by brsysadmin** [comment]
I'm interested by a feature of "custom rules" too :)
Details:
  - I use Android + Rethink DNS
  - sometime we can meet URLs like https://example.tracker.com/?arg1=example1&url=www.google.com&arg3=example2
  - in this context:
     - Rethink DNS will block example.tracker.com
     - I have to manually extract the url www.google.com to be able to reach my website
   - if we can create custom rules we could imagine to say:
     - I want to extract the value after _url=_ and before _&arg3_
 
 In this example the URL is clean (www.google.com) but in the real life the extracted URL needs probably to be sanitized to be usable :)

**Comment by svenjacobs** [comment]
@timonsku @brsysadmin I'm happy to announce that this has been finally implemented in #172 and will be available in v25 😃

**Comment by svenjacobs** [comment]
@timonsku However it's slightly different from what you proposed. When sharing a link with Leon via the share menu and the "copy to clipboard" action is enabled, it will automatically copy the result to the clipboard afterwards. But Leon will not automatically parse the contents of the clipboard when opened normally (not through share menu). If you still need this functionality, please be so kind and open a new issue for it 😃

**Comment by timonsku** [comment]
oh awesome!

**Comment by brsysadmin** [comment]
> @timonsku However it's slightly different from what you proposed. When sharing a link with Leon via the share menu and the "copy to clipboard" action is enabled, it will automatically copy the result to the clipboard afterwards. But Leon will not automatically parse the contents of the clipboard when opened normally (not through share menu). If you still need this functionality, please be so kind and open a new issue for it 😃

Thank you very much :)
I installed the new version this morning: I'll test asap :)
