### ISSUE TITLE
Clean eBay URLs

### ISSUE THREAD

**Issue by Enkidu70** [svenjacobs/leon#72]
Please support full cleaning of eBay URLs.
Means, reduce or rewrite given URL to 

https://www.ebay._DOMAIN_/itm/_ITEMNO_

Example:
* Orig: https://www.ebay.de/itm/271784973135?mkcid=16&mkevt=1&mkrid=707-127654-2357-0&ssspo=rMbbkKXARCW&sssrc=2348624&ssuid=Bw-3_LUXSsm&widget_ver=artemis&media=MORE
* Cleaned: https://www.ebay.de/itm/271784973135

Tnx in advance,
Enkidu

**Comment by svenjacobs** [comment]
[Related](https://github.com/svenjacobs/leon/issues/70#issuecomment-1256122136) to issue #70.

**Comment by svenjacobs** [comment]
This will be available in the next release.
