### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#79]
@svenjacobs Could we get an option for Léon to keep running over the URL until no more change?   Rerunning seems redundant.  E.g., I just got this link via Google Alert in  my GMail:

`https://www.google.com/url?q=https://www.google.com/url?rct%3Dj%26sa%3Dt%26url%3Dhttps://www.inferse.com/268929/prime-day-2022-phone-deals-all-the-best-amazon-prime-early-access-phone-deals-bgr/%26ct%3Dga%26cd%3DCAEYACoUMTA3NzY4NTE0MDEwNTAyODc4MzMyHDMxNGQyNzdmOTRjOGU5MDE6Y29tOmVuOlVTOlI%26usg%3DAOvVaw0ib2-8ukc8GkNkCxTAEkb6&source=gmail&ust=1665828403544000&usg=AOvVaw0R6tQNh7vvWCHGibWcIz_k`

↓ which Léon makes ↓

`https://www.google.com/url?rct=j&sa=t&url=https://www.inferse.com/268929/prime-day-2022-phone-deals-all-the-best-amazon-prime-early-access-phone-deals-bgr/&ct=ga&cd=CAEYACoUMTA3NzY4NTE0MDEwNTAyODc4MzMyHDMxNGQyNzdmOTRjOGU5MDE6Y29tOmVuOlVTOlI&usg=AOvVaw0ib2-8ukc8GkNkCxTAEkb6`

↓ which, when *re*run through Léon, finally ends up @ ↓

`https://www.inferse.com/268929/prime-day-2022-phone-deals-all-the-best-amazon-prime-early-access-phone-deals-bgr/`

**Comment by svenjacobs** [comment]
Interesting use case and good point!

**Comment by svenjacobs** [comment]
Just an FYI, I'm working on this.
