### ISSUE TITLE
GeoRiot tracking

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#82]
@svenjacobs GeoRiot uses a similar, but not identical scheme, to #42.  So 1 might run into

- `https://target.georiot.com/Proxy.ashx?tsid=8429&GR_URL=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0B3Q23BT4%3Ftag%3Dhawk-future-20%26linkCode%3Dogi%26th%3D1%26psc%3D1%26ascsubtag%3Dcbq-us-custom-tracking-20`

which, of course, should just be

- `https://smile.amazon.com/dp/B0B3Q23BT4` (when the `smile` option is on)

So just the url-decoded value of parameter `GR_URL` is required.  Then the 2nd pass from #79 would clean/fix the Amazon URL properly.

**Comment by svenjacobs** [comment]
I recently simplified the [project architecture](https://github.com/svenjacobs/leon/pull/81). Adding new sanitizers should be simple, especially when they are similar to existing ones. A pull request would be very welcomed. Same goes for your others issues #83 and #84. Thank you :)

**Comment by TPS** [comment]
Sadly, I'm no Android _dev_, just a heavy user, so I don't know how I could help this way. 🙇🏾‍♂️
