### ISSUE TITLE
F-Droid - versionName issue

### ISSUE THREAD

**Issue by licaon-kter** [svenjacobs/leon#89]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3261713737#L399

ref: https://github.com/svenjacobs/leon/commit/bf86e5dc4976f926ba5ccbecb2fcf45db3e701e4#diff-8cff73265af19c059547b76aca8882cbaa3209291406f52df1dafbbc78e80c46R39

**Comment by svenjacobs** [comment]
Thanks for the notice. Apparently F-Droid expects the version name to be equal to the version tag.

**Comment by licaon-kter** [comment]
I don't understand...

Your code linked above says: `versionName = latestTagName()` doesn't that mean "the version name to be equal to the version tag" ?

**Comment by svenjacobs** [comment]
The tag is `v17`, that is correct. But `latestTagName()` removes the `v` so the version name becomes `"17"`. But it seems that F-Droid expects the version name to be equal to the tag name.

**Comment by licaon-kter** [comment]
We'd like to get rid of versionName from metadata in the future since it's not important.

**Comment by licaon-kter** [comment]
Running checkupdate yields this:
```
DEBUG: > git checkout -f v17
DEBUG: Directory: build/com.svenjacobs.app.leon
DEBUG: > git clean -dffx
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/build.gradle.kts'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/core-common/build.gradle.kts'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/buildSrc/build.gradle.kts'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/core-domain/src/main/AndroidManifest.xml'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/core-domain/build.gradle.kts'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/core-domain/src/main/AndroidManifest.xml'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/app/src/main/AndroidManifest.xml'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/app/build.gradle.kts'
DEBUG: ..got package=com.svenjacobs.app.leon, version=None, vercode=238
DEBUG: Adding possible subdir app
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/app/src/main/AndroidManifest.xml'
DEBUG: ..got package=None, version=None, vercode=None
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/app/build.gradle.kts'
DEBUG: ..got package=com.svenjacobs.app.leon, version=None, vercode=238
DEBUG: Manifest exists in subdir 'app'. Found version v17 (238)
DEBUG: Parsing manifest at 'build/com.svenjacobs.app.leon/app/src/main/AndroidManifest.xml'
DEBUG: ..got package=None, version=None, vercode=None
```

The thing is that checkupdate does not run functions so it default to the known thing.... the tag

**Comment by svenjacobs** [comment]
Oh, okay. Then I have to think about another solution for the version name.

**Comment by licaon-kter** [comment]
While autoupdates cat be broken we can always edit manually. We approach you, upstream, to maybe find a way so autoupdates are ok, but if not then we/you/users can update manually, with a delay. :)

**Comment by svenjacobs** [comment]
@licaon-kter Thanks for fixing this manually! 👍🏼
