### ISSUE TITLE
Click on Licenses crashes the app 

### ISSUE THREAD

**Issue by guerda** [svenjacobs/leon#90]
If you click on Licenses in the settings, the app crashes.
This happens both whole the app is opened during a share intent and if you open it standalone

Happens on Android 13, Leon Version 1.2.0

**Comment by guerda** [comment]
I see that v17 should fix that based on the  release notes. 
This is not yet on fdroid, correct?

**Comment by svenjacobs** [comment]
Yes, this should actually already be fixed but a [build issue](https://github.com/svenjacobs/leon/issues/89) on F-Droid prevents the current release. `v18` should hopefully be available on F-Droid soon.

**Comment by guerda** [comment]
Newest build from F-Droid works! It shows B-17.

**Comment by svenjacobs** [comment]
Interesting. I thought builds are currently not working (see #89).

**Comment by guerda** [comment]
This is what I'm seeing on F-Droid:

![Screenshot_20221106-142755.png](https://user-images.githubusercontent.com/230782/200173493-c6c31b4d-0c63-49f1-ac2f-ec500e8f3d5e.png)

In the app settings, it is showing version 17, too.

**Comment by svenjacobs** [comment]
Yes, this [was fixed](https://gitlab.com/fdroid/fdroiddata/-/pipelines/683400353) by an F-Droid contributor.
