### ISSUE TITLE
Add Cleaner for converting YT Music to regular YT links

### ISSUE THREAD

**Issue by jakedot** [svenjacobs/leon#98]
Is there a way to add a URL Cleaner for YouTube Music links ([music.youtube.com](http://music.youtube.com/))?

Many people are not familiar with it and would prefer for me to send them my current music tastes using a regular [YouTube.com](https://youtube.com) link.

Also, not all social media platforms recognize and display the preview / video embeds for "music." links.

All that needs to be done is to strip the "music." domain prefix. The music and regular youtube services use all the same URL parameters etc. otherwise.

Thanks for your consideration

**Comment by svenjacobs** [comment]
Thanks @jakedot for your feedback.

Just to be clear, any `music.youtube.com` link can be converted to `youtube.com` by just removing the `music` subdomain while the link still works?

**Comment by jakedot** [comment]
Yes, exactly, that's what I'm using all the time manually.

Am Di., 8. Nov. 2022 um 08:57 Uhr schrieb Sven Jacobs <
***@***.***>:

**Comment by svenjacobs** [comment]
@all-contributors please add @jakedot for ideas
